#!/bin/bash
set -e
HOST_NAME="$1"

if [ $# -gt 1 ]
then
	echo "Terlalu banyak Argumen!"
	exit 0
else
	if [ "$HOST_NAME" != "" ]
	then
		echo $HOST_NAME > /etc/hostname
		echo "tambahkan hostname sukses!"
		cat << @@EOF > /etc/hosts
127.0.0.1 localhost $HOST_NAME

# The following lines are desirable for IPv6 capable hosts
::1     ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
@@EOF

	else
		echo "Err,, HOST_NAME Tidak Boleh Kosong!"
		exit 0
	fi
fi
